/**
 * Ingredient Database for Gezonde Maaltijd App
 *
 * Covers 4 key nutrient categories:
 *   1. Proteins      (eiwitten)
 *   2. Fibers        (vezels)
 *   3. Healthy Fats  (gezonde vetten)
 *   4. Vegetables    (groenten)
 *
 * Nutritional values are approximate per 100 g (raw unless noted).
 * Sources: USDA FoodData Central, Mayo Clinic, Healthline, Voedingscentrum NL.
 *
 * Dietary flags:
 *   vegetarian  – suitable for lacto-ovo vegetarians
 *   vegan       – contains no animal products
 *   dairy       – contains milk / dairy
 *   gluten      – contains gluten
 *   fish        – contains fish or shellfish
 *
 * Score bands (for the primary nutrient column):
 *   "high"   – top tier source
 *   "medium" – decent source
 *   "low"    – minor contributor
 */

// ─────────────────────────────────────────────
// 1. HIGH-PROTEIN INGREDIENTS  (eiwitten)
// ─────────────────────────────────────────────
export const eiwittenIngredients = [
  // ── Poultry ──────────────────────────────────
  {
    id: "chicken_breast",
    dutchName: "Kipfilet",
    englishName: "Chicken breast",
    proteinPer100g: 31,            // g – cooked, skinless
    calories: 165,
    fatPer100g: 3.6,
    carbsPer100g: 0,
    category: "poultry",
    dietaryFlags: [],
    score: "high",
    notes: "Leanest poultry cut; cooked value",
  },
  {
    id: "turkey_breast",
    dutchName: "Kalkoenfilet",
    englishName: "Turkey breast",
    proteinPer100g: 30,
    calories: 157,
    fatPer100g: 3.2,
    carbsPer100g: 0,
    category: "poultry",
    dietaryFlags: [],
    score: "high",
    notes: "Cooked, skinless",
  },
  // ── Red meat ─────────────────────────────────
  {
    id: "beef_sirloin",
    dutchName: "Runderlende",
    englishName: "Beef sirloin",
    proteinPer100g: 29,
    calories: 207,
    fatPer100g: 9.2,
    carbsPer100g: 0,
    category: "red_meat",
    dietaryFlags: [],
    score: "high",
    notes: "Cooked, trimmed of fat",
  },
  {
    id: "beef_mince_lean",
    dutchName: "Mager rundergehakt",
    englishName: "Lean ground beef (5% fat)",
    proteinPer100g: 26,
    calories: 152,
    fatPer100g: 5,
    carbsPer100g: 0,
    category: "red_meat",
    dietaryFlags: [],
    score: "high",
    notes: "Raw, 5% fat variety",
  },
  {
    id: "pork_tenderloin",
    dutchName: "Varkenshaas",
    englishName: "Pork tenderloin",
    proteinPer100g: 26,
    calories: 143,
    fatPer100g: 3.5,
    carbsPer100g: 0,
    category: "red_meat",
    dietaryFlags: [],
    score: "high",
    notes: "One of the leanest pork cuts",
  },
  // ── Fish & seafood ───────────────────────────
  {
    id: "tuna_canned",
    dutchName: "Tonijn (blik, in water)",
    englishName: "Canned tuna in water",
    proteinPer100g: 30,
    calories: 128,
    fatPer100g: 1,
    carbsPer100g: 0,
    category: "fish",
    dietaryFlags: ["fish"],
    score: "high",
    notes: "Drained",
  },
  {
    id: "salmon",
    dutchName: "Zalm",
    englishName: "Salmon (Atlantic, farmed)",
    proteinPer100g: 25,
    calories: 206,
    fatPer100g: 13,
    carbsPer100g: 0,
    category: "fish",
    dietaryFlags: ["fish"],
    score: "high",
    notes: "Also an excellent source of omega-3",
  },
  {
    id: "cod",
    dutchName: "Kabeljauw",
    englishName: "Cod",
    proteinPer100g: 23,
    calories: 105,
    fatPer100g: 0.9,
    carbsPer100g: 0,
    category: "fish",
    dietaryFlags: ["fish"],
    score: "high",
    notes: "Very lean white fish",
  },
  {
    id: "shrimp",
    dutchName: "Garnalen",
    englishName: "Shrimp / prawns",
    proteinPer100g: 24,
    calories: 99,
    fatPer100g: 0.3,
    carbsPer100g: 0.2,
    category: "seafood",
    dietaryFlags: ["fish"],
    score: "high",
    notes: "Cooked",
  },
  {
    id: "mackerel",
    dutchName: "Makreel",
    englishName: "Mackerel",
    proteinPer100g: 19,
    calories: 205,
    fatPer100g: 13,
    carbsPer100g: 0,
    category: "fish",
    dietaryFlags: ["fish"],
    score: "medium",
    notes: "Very high in omega-3 as well",
  },
  // ── Dairy & eggs ─────────────────────────────
  {
    id: "eggs",
    dutchName: "Eieren",
    englishName: "Whole eggs",
    proteinPer100g: 13,
    calories: 155,
    fatPer100g: 11,
    carbsPer100g: 1.1,
    category: "eggs",
    dietaryFlags: ["vegetarian"],
    score: "medium",
    notes: "Whole, raw; complete amino acid profile",
  },
  {
    id: "greek_yogurt",
    dutchName: "Griekse yoghurt (0%)",
    englishName: "Greek yogurt (0% fat)",
    proteinPer100g: 10,
    calories: 59,
    fatPer100g: 0.4,
    carbsPer100g: 3.6,
    category: "dairy",
    dietaryFlags: ["vegetarian", "dairy"],
    score: "medium",
    notes: "Strained, fat-free variety",
  },
  {
    id: "cottage_cheese",
    dutchName: "Kwark / cottage cheese",
    englishName: "Cottage cheese (low-fat)",
    proteinPer100g: 12,
    calories: 98,
    fatPer100g: 2.3,
    carbsPer100g: 3.4,
    category: "dairy",
    dietaryFlags: ["vegetarian", "dairy"],
    score: "medium",
    notes: "Good satiety-to-calorie ratio",
  },
  {
    id: "mozzarella",
    dutchName: "Mozzarella",
    englishName: "Mozzarella (part-skim)",
    proteinPer100g: 22,
    calories: 254,
    fatPer100g: 16,
    carbsPer100g: 2.8,
    category: "dairy",
    dietaryFlags: ["vegetarian", "dairy"],
    score: "high",
    notes: "Part-skim; higher protein than full-fat",
  },
  {
    id: "parmesan",
    dutchName: "Parmezaan",
    englishName: "Parmesan cheese",
    proteinPer100g: 38,
    calories: 431,
    fatPer100g: 29,
    carbsPer100g: 3.2,
    category: "dairy",
    dietaryFlags: ["vegetarian", "dairy"],
    score: "high",
    notes: "Highest protein of common cheeses; calorie-dense",
  },
  // ── Legumes ───────────────────────────────────
  {
    id: "lentils_cooked",
    dutchName: "Linzen (gekookt)",
    englishName: "Lentils (cooked)",
    proteinPer100g: 9,
    calories: 116,
    fatPer100g: 0.4,
    carbsPer100g: 20,
    category: "legumes",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Also high in fiber; cheap and versatile",
  },
  {
    id: "chickpeas_cooked",
    dutchName: "Kikkererwten (gekookt)",
    englishName: "Chickpeas (cooked)",
    proteinPer100g: 9,
    calories: 164,
    fatPer100g: 2.6,
    carbsPer100g: 27,
    category: "legumes",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "High fiber and protein combo",
  },
  {
    id: "black_beans_cooked",
    dutchName: "Zwarte bonen (gekookt)",
    englishName: "Black beans (cooked)",
    proteinPer100g: 9,
    calories: 132,
    fatPer100g: 0.5,
    carbsPer100g: 24,
    category: "legumes",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "High antioxidant content",
  },
  // ── Plant-based proteins ──────────────────────
  {
    id: "tofu_firm",
    dutchName: "Tofu (stevig)",
    englishName: "Firm tofu",
    proteinPer100g: 17,
    calories: 144,
    fatPer100g: 9,
    carbsPer100g: 2,
    category: "plant_protein",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Also contains all essential amino acids",
  },
  {
    id: "tempeh",
    dutchName: "Tempeh",
    englishName: "Tempeh",
    proteinPer100g: 19,
    calories: 193,
    fatPer100g: 11,
    carbsPer100g: 9,
    category: "plant_protein",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Fermented soy; improves gut health; nutty texture",
  },
  {
    id: "edamame",
    dutchName: "Edamame (gekookt)",
    englishName: "Edamame (cooked soybeans)",
    proteinPer100g: 11,
    calories: 122,
    fatPer100g: 5.2,
    carbsPer100g: 8.9,
    category: "plant_protein",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Young soybeans; also contains fiber",
  },
  {
    id: "hemp_seeds",
    dutchName: "Hennepzaden",
    englishName: "Hemp seeds (hulled)",
    proteinPer100g: 31,
    calories: 553,
    fatPer100g: 49,
    carbsPer100g: 8.7,
    category: "seeds",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Complete protein; also rich in omega-3/6",
  },
  {
    id: "pumpkin_seeds",
    dutchName: "Pompoenpitten",
    englishName: "Pumpkin seeds",
    proteinPer100g: 30,
    calories: 559,
    fatPer100g: 49,
    carbsPer100g: 11,
    category: "seeds",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "High in zinc and magnesium too",
  },
];

// ─────────────────────────────────────────────
// 2. HIGH-FIBER INGREDIENTS  (vezels)
// ─────────────────────────────────────────────
export const vezelsIngredients = [
  // ── Seeds & husks ────────────────────────────
  {
    id: "chia_seeds",
    dutchName: "Chiazaad",
    englishName: "Chia seeds",
    fiberPer100g: 34,
    calories: 486,
    proteinPer100g: 17,
    fatPer100g: 31,
    category: "seeds",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble + insoluble",
    notes: "Absorb water and form gel; great in puddings",
  },
  {
    id: "flaxseeds",
    dutchName: "Lijnzaad",
    englishName: "Flaxseeds (ground)",
    fiberPer100g: 27,
    calories: 534,
    proteinPer100g: 18,
    fatPer100g: 42,
    category: "seeds",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble + insoluble",
    notes: "Grind before eating for bioavailability; rich in ALA omega-3",
  },
  {
    id: "psyllium_husk",
    dutchName: "Psylliumvezels",
    englishName: "Psyllium husk",
    fiberPer100g: 78,
    calories: 200,
    proteinPer100g: 2,
    fatPer100g: 0.5,
    category: "supplement",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble",
    notes: "Concentrated fiber supplement; use in small quantities",
  },
  // ── Legumes ───────────────────────────────────
  {
    id: "black_beans_dry",
    dutchName: "Zwarte bonen (droog)",
    englishName: "Black beans (dry)",
    fiberPer100g: 16,
    calories: 341,
    proteinPer100g: 21,
    fatPer100g: 1.4,
    category: "legumes",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble + insoluble",
    notes: "Dry weight; cook before eating",
  },
  {
    id: "kidney_beans_dry",
    dutchName: "Kidneybonen (droog)",
    englishName: "Kidney beans (dry)",
    fiberPer100g: 15,
    calories: 337,
    proteinPer100g: 24,
    fatPer100g: 1.1,
    category: "legumes",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble + insoluble",
    notes: "Dry weight; must be boiled thoroughly",
  },
  {
    id: "split_peas_dry",
    dutchName: "Spliterwten (droog)",
    englishName: "Split peas (dry)",
    fiberPer100g: 26,
    calories: 341,
    proteinPer100g: 25,
    fatPer100g: 1.1,
    category: "legumes",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble",
    notes: "Classic Dutch erwtensoep base",
  },
  {
    id: "lentils_dry",
    dutchName: "Linzen (droog)",
    englishName: "Lentils (dry)",
    fiberPer100g: 11,
    calories: 352,
    proteinPer100g: 26,
    fatPer100g: 1.1,
    category: "legumes",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble + insoluble",
    notes: "Fast-cooking; no soaking needed",
  },
  {
    id: "chickpeas_dry",
    dutchName: "Kikkererwten (droog)",
    englishName: "Chickpeas (dry)",
    fiberPer100g: 17,
    calories: 364,
    proteinPer100g: 19,
    fatPer100g: 6,
    category: "legumes",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble + insoluble",
    notes: "Soak 12h before cooking",
  },
  // ── Grains & bran ────────────────────────────
  {
    id: "oat_bran",
    dutchName: "Haverzemelen",
    englishName: "Oat bran",
    fiberPer100g: 17,
    calories: 246,
    proteinPer100g: 17,
    fatPer100g: 7,
    category: "grains",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble (beta-glucan)",
    notes: "Proven cholesterol-lowering effect",
  },
  {
    id: "rolled_oats",
    dutchName: "Havervlokken",
    englishName: "Rolled oats",
    fiberPer100g: 10,
    calories: 389,
    proteinPer100g: 17,
    fatPer100g: 7,
    category: "grains",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble (beta-glucan)",
    notes: "Contains gluten-like avenin; check label for gluten-free oats",
  },
  {
    id: "whole_wheat",
    dutchName: "Volkorenmeel",
    englishName: "Whole wheat flour",
    fiberPer100g: 11,
    calories: 340,
    proteinPer100g: 13,
    fatPer100g: 2.5,
    category: "grains",
    dietaryFlags: ["vegetarian", "vegan", "gluten"],
    score: "high",
    fiberType: "insoluble",
    notes: "Use instead of white flour for 3× more fiber",
  },
  {
    id: "quinoa",
    dutchName: "Quinoa",
    englishName: "Quinoa",
    fiberPer100g: 7,
    calories: 368,
    proteinPer100g: 14,
    fatPer100g: 6,
    category: "grains",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    fiberType: "insoluble",
    notes: "Gluten-free pseudo-grain; complete protein",
  },
  {
    id: "amaranth",
    dutchName: "Amarant",
    englishName: "Amaranth",
    fiberPer100g: 7,
    calories: 371,
    proteinPer100g: 14,
    fatPer100g: 7,
    category: "grains",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    fiberType: "insoluble",
    notes: "Gluten-free ancient grain",
  },
  // ── Nuts ─────────────────────────────────────
  {
    id: "almonds",
    dutchName: "Amandelen",
    englishName: "Almonds",
    fiberPer100g: 13,
    calories: 579,
    proteinPer100g: 21,
    fatPer100g: 50,
    category: "nuts",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "insoluble",
    notes: "Also rich in vitamin E and healthy fats",
  },
  {
    id: "pistachios",
    dutchName: "Pistachenoten",
    englishName: "Pistachios",
    fiberPer100g: 10,
    calories: 562,
    proteinPer100g: 20,
    fatPer100g: 45,
    category: "nuts",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "insoluble",
    notes: "Lower calorie nut; fun to shell",
  },
  {
    id: "hazelnuts",
    dutchName: "Hazelnoten",
    englishName: "Hazelnuts",
    fiberPer100g: 10,
    calories: 628,
    proteinPer100g: 15,
    fatPer100g: 61,
    category: "nuts",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "insoluble",
    notes: "Rich in vitamin E and manganese",
  },
  // ── Dried fruits ─────────────────────────────
  {
    id: "dried_figs",
    dutchName: "Gedroogde vijgen",
    englishName: "Dried figs",
    fiberPer100g: 10,
    calories: 249,
    proteinPer100g: 3.3,
    fatPer100g: 0.9,
    category: "dried_fruit",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble + insoluble",
    notes: "Also high in calcium and potassium",
  },
  {
    id: "prunes",
    dutchName: "Pruimen (gedroogd)",
    englishName: "Prunes (dried)",
    fiberPer100g: 7,
    calories: 240,
    proteinPer100g: 2.2,
    fatPer100g: 0.4,
    category: "dried_fruit",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    fiberType: "soluble",
    notes: "Known laxative effect; contains sorbitol",
  },
  // ── Vegetables (high-fiber) ───────────────────
  {
    id: "green_peas_raw",
    dutchName: "Doperwten",
    englishName: "Green peas (raw)",
    fiberPer100g: 5.5,
    calories: 81,
    proteinPer100g: 5.4,
    fatPer100g: 0.4,
    category: "vegetables",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    fiberType: "soluble + insoluble",
    notes: "Great in stews, soups and rice dishes",
  },
  {
    id: "avocado",
    dutchName: "Avocado",
    englishName: "Avocado",
    fiberPer100g: 6.7,
    calories: 160,
    proteinPer100g: 2,
    fatPer100g: 15,
    category: "fruit",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    fiberType: "soluble",
    notes: "Also very high in monounsaturated fats",
  },
  {
    id: "artichoke",
    dutchName: "Artisjok",
    englishName: "Globe artichoke",
    fiberPer100g: 8.6,
    calories: 47,
    proteinPer100g: 3.3,
    fatPer100g: 0.2,
    category: "vegetables",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    fiberType: "soluble (inulin)",
    notes: "Excellent prebiotic; feeds gut bacteria",
  },
  {
    id: "broccoli",
    dutchName: "Broccoli",
    englishName: "Broccoli",
    fiberPer100g: 2.6,
    calories: 34,
    proteinPer100g: 2.8,
    fatPer100g: 0.4,
    category: "vegetables",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "low",
    fiberType: "soluble + insoluble",
    notes: "Also excellent for cruciferous phytonutrients",
  },
  {
    id: "raspberries",
    dutchName: "Frambozen",
    englishName: "Raspberries",
    fiberPer100g: 6.5,
    calories: 52,
    proteinPer100g: 1.2,
    fatPer100g: 0.7,
    category: "fruit",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    fiberType: "insoluble",
    notes: "Highest fiber of common berries",
  },
  {
    id: "blackberries",
    dutchName: "Bramen",
    englishName: "Blackberries",
    fiberPer100g: 5.3,
    calories: 43,
    proteinPer100g: 1.4,
    fatPer100g: 0.5,
    category: "fruit",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    fiberType: "insoluble",
    notes: "High in vitamin C and antioxidants",
  },
];

// ─────────────────────────────────────────────
// 3. HEALTHY FAT INGREDIENTS  (gezonde vetten)
// ─────────────────────────────────────────────
export const gezondeVettenIngredients = [
  // ── Oils ─────────────────────────────────────
  {
    id: "olive_oil_extra_virgin",
    dutchName: "Extra vergine olijfolie",
    englishName: "Extra virgin olive oil",
    totalFatPer100g: 100,
    saturatedFat: 14,
    monounsaturatedFat: 73,
    polyunsaturatedFat: 11,
    omega3Per100g: 0.76,             // g
    fatType: "monounsaturated (MUFA)",
    calories: 884,
    category: "oils",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Rich in oleocanthal (anti-inflammatory); cornerstone of Mediterranean diet",
  },
  {
    id: "flaxseed_oil",
    dutchName: "Lijnzaadolie",
    englishName: "Flaxseed oil",
    totalFatPer100g: 100,
    saturatedFat: 9,
    monounsaturatedFat: 18,
    polyunsaturatedFat: 68,
    omega3Per100g: 53,
    fatType: "polyunsaturated – ALA omega-3",
    calories: 884,
    category: "oils",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Highest plant omega-3; do not heat; store in fridge",
  },
  {
    id: "walnut_oil",
    dutchName: "Walnootolie",
    englishName: "Walnut oil",
    totalFatPer100g: 100,
    saturatedFat: 9,
    monounsaturatedFat: 22,
    polyunsaturatedFat: 63,
    omega3Per100g: 10.4,
    fatType: "polyunsaturated – omega-3/6",
    calories: 884,
    category: "oils",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Good omega-3/6 balance; use cold",
  },
  // ── Fatty fish ───────────────────────────────
  {
    id: "salmon_fatty",
    dutchName: "Zalm (vette vis)",
    englishName: "Atlantic salmon",
    totalFatPer100g: 13,
    saturatedFat: 3.1,
    monounsaturatedFat: 4.8,
    polyunsaturatedFat: 3.9,
    omega3Per100g: 2.5,             // EPA+DHA
    fatType: "polyunsaturated – EPA/DHA omega-3",
    calories: 206,
    proteinPer100g: 25,
    category: "fish",
    dietaryFlags: ["fish"],
    score: "high",
    notes: "Best dietary source of EPA+DHA",
  },
  {
    id: "mackerel_fatty",
    dutchName: "Makreel",
    englishName: "Atlantic mackerel",
    totalFatPer100g: 14,
    saturatedFat: 3.3,
    monounsaturatedFat: 5.5,
    polyunsaturatedFat: 3.4,
    omega3Per100g: 2.7,             // EPA+DHA
    fatType: "polyunsaturated – EPA/DHA omega-3",
    calories: 205,
    proteinPer100g: 19,
    category: "fish",
    dietaryFlags: ["fish"],
    score: "high",
    notes: "Highest omega-3 per 100g of common fish",
  },
  {
    id: "sardines",
    dutchName: "Sardines",
    englishName: "Sardines (canned in olive oil)",
    totalFatPer100g: 11,
    saturatedFat: 2.3,
    monounsaturatedFat: 4.2,
    polyunsaturatedFat: 3.3,
    omega3Per100g: 1.8,             // EPA+DHA
    fatType: "polyunsaturated – EPA/DHA omega-3",
    calories: 208,
    proteinPer100g: 25,
    category: "fish",
    dietaryFlags: ["fish"],
    score: "high",
    notes: "Cheap, sustainable, also rich in calcium (bones)",
  },
  {
    id: "herring",
    dutchName: "Haring",
    englishName: "Herring",
    totalFatPer100g: 17,
    saturatedFat: 3.8,
    monounsaturatedFat: 7.4,
    polyunsaturatedFat: 4.0,
    omega3Per100g: 2.0,
    fatType: "polyunsaturated – EPA/DHA omega-3",
    calories: 217,
    proteinPer100g: 18,
    category: "fish",
    dietaryFlags: ["fish"],
    score: "high",
    notes: "Classic Dutch 'Hollandse Nieuwe'; very sustainable",
  },
  // ── Nuts ─────────────────────────────────────
  {
    id: "walnuts",
    dutchName: "Walnoten",
    englishName: "Walnuts",
    totalFatPer100g: 65,
    saturatedFat: 6.1,
    monounsaturatedFat: 8.9,
    polyunsaturatedFat: 47,
    omega3Per100g: 9.1,             // ALA
    fatType: "polyunsaturated – ALA omega-3",
    calories: 654,
    proteinPer100g: 15,
    category: "nuts",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Highest omega-3 nut; brain-shaped, brain-beneficial",
  },
  {
    id: "almonds_fat",
    dutchName: "Amandelen",
    englishName: "Almonds",
    totalFatPer100g: 50,
    saturatedFat: 3.8,
    monounsaturatedFat: 31,
    polyunsaturatedFat: 12,
    omega3Per100g: 0.0,
    fatType: "monounsaturated (MUFA)",
    calories: 579,
    proteinPer100g: 21,
    category: "nuts",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Rich in vitamin E; best eaten unsalted, unroasted",
  },
  {
    id: "macadamia_nuts",
    dutchName: "Macadamianoten",
    englishName: "Macadamia nuts",
    totalFatPer100g: 76,
    saturatedFat: 12,
    monounsaturatedFat: 59,
    polyunsaturatedFat: 1.5,
    omega3Per100g: 0.2,
    fatType: "monounsaturated (MUFA)",
    calories: 718,
    proteinPer100g: 8,
    category: "nuts",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Highest MUFA of any nut",
  },
  {
    id: "cashews",
    dutchName: "Cashewnoten",
    englishName: "Cashews",
    totalFatPer100g: 44,
    saturatedFat: 7.8,
    monounsaturatedFat: 24,
    polyunsaturatedFat: 7.8,
    omega3Per100g: 0.2,
    fatType: "monounsaturated (MUFA)",
    calories: 553,
    proteinPer100g: 18,
    category: "nuts",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Good source of zinc and magnesium",
  },
  {
    id: "pecans",
    dutchName: "Pecannoten",
    englishName: "Pecans",
    totalFatPer100g: 72,
    saturatedFat: 6.2,
    monounsaturatedFat: 41,
    polyunsaturatedFat: 21,
    omega3Per100g: 1.0,
    fatType: "monounsaturated (MUFA)",
    calories: 691,
    proteinPer100g: 9,
    category: "nuts",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Rich in manganese and antioxidants",
  },
  {
    id: "hazelnuts_fat",
    dutchName: "Hazelnoten",
    englishName: "Hazelnuts",
    totalFatPer100g: 61,
    saturatedFat: 4.5,
    monounsaturatedFat: 46,
    polyunsaturatedFat: 8,
    omega3Per100g: 0.1,
    fatType: "monounsaturated (MUFA)",
    calories: 628,
    proteinPer100g: 15,
    category: "nuts",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Second highest MUFA after macadamia",
  },
  // ── Seeds ────────────────────────────────────
  {
    id: "chia_seeds_fat",
    dutchName: "Chiazaad",
    englishName: "Chia seeds",
    totalFatPer100g: 31,
    saturatedFat: 3.3,
    monounsaturatedFat: 2.3,
    polyunsaturatedFat: 24,
    omega3Per100g: 18,              // ALA
    fatType: "polyunsaturated – ALA omega-3",
    calories: 486,
    proteinPer100g: 17,
    category: "seeds",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "One of the richest plant omega-3 sources per gram",
  },
  {
    id: "flaxseeds_fat",
    dutchName: "Lijnzaad (gemalen)",
    englishName: "Ground flaxseeds",
    totalFatPer100g: 42,
    saturatedFat: 3.7,
    monounsaturatedFat: 7.5,
    polyunsaturatedFat: 29,
    omega3Per100g: 22.8,            // ALA
    fatType: "polyunsaturated – ALA omega-3",
    calories: 534,
    proteinPer100g: 18,
    category: "seeds",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Grind for full nutrient absorption",
  },
  {
    id: "hemp_seeds_fat",
    dutchName: "Hennepzaden",
    englishName: "Hemp seeds (hulled)",
    totalFatPer100g: 49,
    saturatedFat: 4.6,
    monounsaturatedFat: 5.6,
    polyunsaturatedFat: 38,
    omega3Per100g: 8.7,             // ALA
    fatType: "polyunsaturated – ALA omega-3",
    calories: 553,
    proteinPer100g: 31,
    category: "seeds",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Ideal omega-3:6 ratio (1:3); also complete protein",
  },
  {
    id: "sesame_seeds",
    dutchName: "Sesamzaad",
    englishName: "Sesame seeds",
    totalFatPer100g: 50,
    saturatedFat: 7,
    monounsaturatedFat: 19,
    polyunsaturatedFat: 22,
    omega3Per100g: 0.4,
    fatType: "polyunsaturated (PUFA)",
    calories: 573,
    proteinPer100g: 17,
    category: "seeds",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Rich in lignans; strong antioxidant sesamin",
  },
  // ── Fruit ────────────────────────────────────
  {
    id: "avocado_fat",
    dutchName: "Avocado",
    englishName: "Avocado",
    totalFatPer100g: 15,
    saturatedFat: 2.1,
    monounsaturatedFat: 9.8,
    polyunsaturatedFat: 1.8,
    omega3Per100g: 0.1,
    fatType: "monounsaturated (MUFA)",
    calories: 160,
    proteinPer100g: 2,
    category: "fruit",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Only common fruit with significant healthy fat; also high fiber + potassium",
  },
  {
    id: "olives",
    dutchName: "Olijven (zwart)",
    englishName: "Black olives",
    totalFatPer100g: 11,
    saturatedFat: 1.5,
    monounsaturatedFat: 7.9,
    polyunsaturatedFat: 0.9,
    omega3Per100g: 0.1,
    fatType: "monounsaturated (MUFA)",
    calories: 145,
    proteinPer100g: 1,
    category: "fruit",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Whole food form of olive oil; high in sodium when canned",
  },
  // ── Dairy ────────────────────────────────────
  {
    id: "full_fat_yogurt",
    dutchName: "Volle Griekse yoghurt",
    englishName: "Full-fat Greek yogurt",
    totalFatPer100g: 10,
    saturatedFat: 6.5,
    monounsaturatedFat: 2.8,
    polyunsaturatedFat: 0.3,
    omega3Per100g: 0.05,
    fatType: "saturated + monounsaturated",
    calories: 130,
    proteinPer100g: 9,
    category: "dairy",
    dietaryFlags: ["vegetarian", "dairy"],
    score: "medium",
    notes: "Dairy fat increasingly viewed as neutral/positive; high CLA content",
  },
  {
    id: "dark_chocolate_85",
    dutchName: "Pure chocolade (85%)",
    englishName: "Dark chocolate (85% cacao)",
    totalFatPer100g: 43,
    saturatedFat: 24,
    monounsaturatedFat: 13,
    polyunsaturatedFat: 1.3,
    omega3Per100g: 0.1,
    fatType: "saturated + monounsaturated",
    calories: 598,
    proteinPer100g: 11,
    category: "other",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Rich in stearic acid (neutral saturated fat) and flavonoids; moderate amounts only",
  },
  {
    id: "coconut_oil",
    dutchName: "Kokosolie",
    englishName: "Coconut oil (virgin)",
    totalFatPer100g: 100,
    saturatedFat: 87,
    monounsaturatedFat: 6,
    polyunsaturatedFat: 1.8,
    omega3Per100g: 0,
    fatType: "saturated (MCT)",
    calories: 862,
    proteinPer100g: 0,
    category: "oils",
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "High in MCTs; controversial; use in moderation",
  },
];

// ─────────────────────────────────────────────
// 4. VEGETABLES  (groenten)
// ─────────────────────────────────────────────
export const groenten = [
  // ── Leafy greens (Bladgroenten) ───────────────
  {
    id: "spinach",
    dutchName: "Spinazie",
    englishName: "Spinach",
    category: "leafy_greens",
    calories: 23,
    proteinPer100g: 2.9,
    fiberPer100g: 2.2,
    fatPer100g: 0.4,
    carbsPer100g: 3.6,
    keyNutrients: ["vitamine K", "vitamine A", "folaat", "ijzer", "magnesium"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "One of the most nutrient-dense vegetables per calorie",
  },
  {
    id: "kale",
    dutchName: "Boerenkool",
    englishName: "Kale",
    category: "leafy_greens",
    calories: 49,
    proteinPer100g: 4.3,
    fiberPer100g: 3.6,
    fatPer100g: 0.9,
    carbsPer100g: 9,
    keyNutrients: ["vitamine K", "vitamine C", "vitamine A", "calcium", "antioxidanten"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Dutch staple; traditionally in 'boerenkoolstamppot'",
  },
  {
    id: "swiss_chard",
    dutchName: "Snijbiet / Mangold",
    englishName: "Swiss chard",
    category: "leafy_greens",
    calories: 19,
    proteinPer100g: 1.8,
    fiberPer100g: 1.6,
    fatPer100g: 0.2,
    carbsPer100g: 3.7,
    keyNutrients: ["vitamine K", "vitamine A", "vitamine C", "magnesium"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Colourful stems; milder than kale",
  },
  {
    id: "arugula",
    dutchName: "Rucola",
    englishName: "Arugula (rocket)",
    category: "leafy_greens",
    calories: 25,
    proteinPer100g: 2.6,
    fiberPer100g: 1.6,
    fatPer100g: 0.7,
    carbsPer100g: 3.7,
    keyNutrients: ["vitamine K", "vitamine A", "folaat", "calcium"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Peppery flavour; popular in salads",
  },
  {
    id: "lettuce_romaine",
    dutchName: "Romaine sla",
    englishName: "Romaine lettuce",
    category: "leafy_greens",
    calories: 17,
    proteinPer100g: 1.2,
    fiberPer100g: 2.1,
    fatPer100g: 0.3,
    carbsPer100g: 3.3,
    keyNutrients: ["vitamine K", "vitamine A", "folaat"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Higher nutrient density than iceberg",
  },
  {
    id: "watercress",
    dutchName: "Waterkers",
    englishName: "Watercress",
    category: "leafy_greens",
    calories: 11,
    proteinPer100g: 2.3,
    fiberPer100g: 0.5,
    fatPer100g: 0.1,
    carbsPer100g: 1.3,
    keyNutrients: ["vitamine K", "vitamine C", "vitamine A", "calcium"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Ranked #1 in USDA powerhouse vegetable study",
  },
  // ── Cruciferous (Koolsoorten) ─────────────────
  {
    id: "broccoli_veg",
    dutchName: "Broccoli",
    englishName: "Broccoli",
    category: "cruciferous",
    calories: 34,
    proteinPer100g: 2.8,
    fiberPer100g: 2.6,
    fatPer100g: 0.4,
    carbsPer100g: 6.6,
    keyNutrients: ["vitamine C", "vitamine K", "folaat", "sulforafaan"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Sulforaphane is a potent anti-cancer compound",
  },
  {
    id: "cauliflower",
    dutchName: "Bloemkool",
    englishName: "Cauliflower",
    category: "cruciferous",
    calories: 25,
    proteinPer100g: 1.9,
    fiberPer100g: 2,
    fatPer100g: 0.3,
    carbsPer100g: 5,
    keyNutrients: ["vitamine C", "vitamine K", "folaat", "choline"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Versatile low-carb substitute (cauliflower rice)",
  },
  {
    id: "brussels_sprouts",
    dutchName: "Spruitjes",
    englishName: "Brussels sprouts",
    category: "cruciferous",
    calories: 43,
    proteinPer100g: 3.4,
    fiberPer100g: 3.8,
    fatPer100g: 0.3,
    carbsPer100g: 9,
    keyNutrients: ["vitamine K", "vitamine C", "vitamine A", "folaat"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Highest fiber of common cruciferous; classic Dutch veggie",
  },
  {
    id: "cabbage_white",
    dutchName: "Witte kool",
    englishName: "White cabbage",
    category: "cruciferous",
    calories: 25,
    proteinPer100g: 1.3,
    fiberPer100g: 2.5,
    fatPer100g: 0.1,
    carbsPer100g: 5.8,
    keyNutrients: ["vitamine C", "vitamine K", "folaat"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Very cheap; great fermented as zuurkool (sauerkraut)",
  },
  {
    id: "red_cabbage",
    dutchName: "Rode kool",
    englishName: "Red cabbage",
    category: "cruciferous",
    calories: 31,
    proteinPer100g: 1.4,
    fiberPer100g: 2.1,
    fatPer100g: 0.2,
    carbsPer100g: 7.4,
    keyNutrients: ["vitamine C", "vitamine K", "anthocyaninen", "folaat"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Rich in anthocyanins; classic Dutch 'rodekool met appeltjes'",
  },
  {
    id: "bok_choy",
    dutchName: "Paksoi",
    englishName: "Bok choy (pak choi)",
    category: "cruciferous",
    calories: 13,
    proteinPer100g: 1.5,
    fiberPer100g: 1,
    fatPer100g: 0.2,
    carbsPer100g: 2.2,
    keyNutrients: ["vitamine C", "vitamine A", "vitamine K", "calcium"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Popular in Asian cuisine; also great stir-fried",
  },
  // ── Root vegetables (Wortelgewassen) ──────────
  {
    id: "carrot",
    dutchName: "Wortel",
    englishName: "Carrot",
    category: "root_vegetables",
    calories: 41,
    proteinPer100g: 0.9,
    fiberPer100g: 2.8,
    fatPer100g: 0.2,
    carbsPer100g: 9.6,
    keyNutrients: ["bèta-caroteen (vitamine A)", "vitamine K", "kalium", "antioxidanten"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Beta-carotene absorption increases with a little fat",
  },
  {
    id: "beetroot",
    dutchName: "Rode biet",
    englishName: "Beetroot",
    category: "root_vegetables",
    calories: 43,
    proteinPer100g: 1.6,
    fiberPer100g: 2.8,
    fatPer100g: 0.2,
    carbsPer100g: 9.6,
    keyNutrients: ["folaat", "mangaan", "nitraten", "betalaine"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Dietary nitrates boost athletic endurance",
  },
  {
    id: "parsnip",
    dutchName: "Pastinaak",
    englishName: "Parsnip",
    category: "root_vegetables",
    calories: 75,
    proteinPer100g: 1.2,
    fiberPer100g: 4.9,
    fatPer100g: 0.3,
    carbsPer100g: 18,
    keyNutrients: ["vitamine C", "folaat", "mangaan", "vezels"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Higher fiber than most root vegetables",
  },
  {
    id: "sweet_potato",
    dutchName: "Zoete aardappel",
    englishName: "Sweet potato",
    category: "root_vegetables",
    calories: 86,
    proteinPer100g: 1.6,
    fiberPer100g: 3,
    fatPer100g: 0.1,
    carbsPer100g: 20,
    keyNutrients: ["bèta-caroteen", "vitamine C", "kalium", "mangaan"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Lower GI than regular potato; great antioxidant source",
  },
  {
    id: "celeriac",
    dutchName: "Knolselderij",
    englishName: "Celeriac",
    category: "root_vegetables",
    calories: 42,
    proteinPer100g: 1.5,
    fiberPer100g: 1.8,
    fatPer100g: 0.3,
    carbsPer100g: 9.2,
    keyNutrients: ["vitamine K", "vitamine C", "fosfor", "kalium"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Very popular in Dutch cooking; good in soups and purees",
  },
  {
    id: "turnip",
    dutchName: "Raap",
    englishName: "Turnip",
    category: "root_vegetables",
    calories: 28,
    proteinPer100g: 0.9,
    fiberPer100g: 1.8,
    fatPer100g: 0.1,
    carbsPer100g: 6.4,
    keyNutrients: ["vitamine C", "vitamine K", "folaat"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "low",
    notes: "Low calorie; both root and greens are edible",
  },
  {
    id: "radish",
    dutchName: "Radijs",
    englishName: "Radish",
    category: "root_vegetables",
    calories: 16,
    proteinPer100g: 0.7,
    fiberPer100g: 1.6,
    fatPer100g: 0.1,
    carbsPer100g: 3.4,
    keyNutrients: ["vitamine C", "folaat", "antioxidanten"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "low",
    notes: "Peppery crunch; great raw in salads",
  },
  // ── Alliums (Uitsoorten) ──────────────────────
  {
    id: "onion",
    dutchName: "Ui",
    englishName: "Onion",
    category: "alliums",
    calories: 40,
    proteinPer100g: 1.1,
    fiberPer100g: 1.7,
    fatPer100g: 0.1,
    carbsPer100g: 9.3,
    keyNutrients: ["quercetine", "vitamine C", "vitamine B6", "inuline (prebiotisch)"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Quercetin is a potent anti-inflammatory flavonoid",
  },
  {
    id: "garlic",
    dutchName: "Knoflook",
    englishName: "Garlic",
    category: "alliums",
    calories: 149,
    proteinPer100g: 6.4,
    fiberPer100g: 2.1,
    fatPer100g: 0.5,
    carbsPer100g: 33,
    keyNutrients: ["allicine", "mangaan", "vitamine B6", "vitamine C"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Allicin is a powerful immune-boosting compound; used in small amounts",
  },
  {
    id: "leek",
    dutchName: "Prei",
    englishName: "Leek",
    category: "alliums",
    calories: 61,
    proteinPer100g: 1.5,
    fiberPer100g: 1.8,
    fatPer100g: 0.3,
    carbsPer100g: 14,
    keyNutrients: ["vitamine K", "vitamine A", "folaat", "mangaan"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Mild allium; very popular in Dutch soups and stews",
  },
  {
    id: "shallot",
    dutchName: "Sjalot",
    englishName: "Shallot",
    category: "alliums",
    calories: 72,
    proteinPer100g: 2.5,
    fiberPer100g: 3.2,
    fatPer100g: 0.1,
    carbsPer100g: 17,
    keyNutrients: ["quercetine", "allicine", "vitamine B6", "folaat"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "More flavourful than onion; higher in quercetin",
  },
  // ── Fruiting vegetables (Vruchtgroenten) ──────
  {
    id: "bell_pepper_red",
    dutchName: "Rode paprika",
    englishName: "Red bell pepper",
    category: "fruiting_vegetables",
    calories: 31,
    proteinPer100g: 1,
    fiberPer100g: 2.1,
    fatPer100g: 0.3,
    carbsPer100g: 6,
    keyNutrients: ["vitamine C (3× dagelijkse behoefte)", "vitamine A", "vitamine B6", "antioxidanten"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Highest vitamin C of common vegetables (190 mg/100g)",
  },
  {
    id: "tomato",
    dutchName: "Tomaat",
    englishName: "Tomato",
    category: "fruiting_vegetables",
    calories: 18,
    proteinPer100g: 0.9,
    fiberPer100g: 1.2,
    fatPer100g: 0.2,
    carbsPer100g: 3.9,
    keyNutrients: ["lycopeen", "vitamine C", "vitamine K", "kalium"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Lycopene bioavailability increases when cooked with fat",
  },
  {
    id: "zucchini",
    dutchName: "Courgette",
    englishName: "Zucchini (courgette)",
    category: "fruiting_vegetables",
    calories: 17,
    proteinPer100g: 1.2,
    fiberPer100g: 1.1,
    fatPer100g: 0.3,
    carbsPer100g: 3.1,
    keyNutrients: ["vitamine C", "vitamine A", "mangaan", "folaat"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "low",
    notes: "Very low calorie; great spiralised as pasta alternative",
  },
  {
    id: "eggplant",
    dutchName: "Aubergine",
    englishName: "Eggplant (aubergine)",
    category: "fruiting_vegetables",
    calories: 25,
    proteinPer100g: 1,
    fiberPer100g: 3,
    fatPer100g: 0.2,
    carbsPer100g: 5.9,
    keyNutrients: ["nasunine (antioxidant)", "mangaan", "folaat", "vitamine C"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Nasunin protects brain cell membranes",
  },
  {
    id: "cucumber",
    dutchName: "Komkommer",
    englishName: "Cucumber",
    category: "fruiting_vegetables",
    calories: 15,
    proteinPer100g: 0.7,
    fiberPer100g: 0.5,
    fatPer100g: 0.1,
    carbsPer100g: 3.6,
    keyNutrients: ["vitamine K", "vitamine C", "kalium"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "low",
    notes: "96% water; very hydrating; light nutrient density",
  },
  // ── Stalk vegetables (Stengelgroenten) ────────
  {
    id: "celery",
    dutchName: "Bleekselderij",
    englishName: "Celery",
    category: "stalk_vegetables",
    calories: 16,
    proteinPer100g: 0.7,
    fiberPer100g: 1.6,
    fatPer100g: 0.2,
    carbsPer100g: 3,
    keyNutrients: ["vitamine K", "vitamine C", "folaat", "apigenine"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "low",
    notes: "Negative calorie myth aside, very low energy density",
  },
  {
    id: "asparagus",
    dutchName: "Asperge",
    englishName: "Asparagus",
    category: "stalk_vegetables",
    calories: 20,
    proteinPer100g: 2.2,
    fiberPer100g: 2.1,
    fatPer100g: 0.1,
    carbsPer100g: 3.9,
    keyNutrients: ["folaat", "vitamine K", "vitamine C", "inuline"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Top folate source; prebiotic inulin feeds good gut bacteria; Dutch white asparagus ('witte asperges') a seasonal delicacy",
  },
  {
    id: "fennel",
    dutchName: "Venkel",
    englishName: "Fennel",
    category: "stalk_vegetables",
    calories: 31,
    proteinPer100g: 1.2,
    fiberPer100g: 3.1,
    fatPer100g: 0.2,
    carbsPer100g: 7.3,
    keyNutrients: ["vitamine C", "vitamine K", "kalium", "folaat"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Anise flavour; all parts edible (bulb, stalks, fronds)",
  },
  // ── Mushrooms (Paddenstoelen) ──────────────────
  {
    id: "mushroom_white",
    dutchName: "Champignon",
    englishName: "White mushroom",
    category: "mushrooms",
    calories: 22,
    proteinPer100g: 3.1,
    fiberPer100g: 1,
    fatPer100g: 0.3,
    carbsPer100g: 3.3,
    keyNutrients: ["vitamine D (UV-blootgesteld)", "selenium", "vitamine B2", "ergothioneine"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Place in sunlight 15 min to boost vitamin D; highest ergothioneine antioxidant",
  },
  {
    id: "shiitake",
    dutchName: "Shiitake paddestoel",
    englishName: "Shiitake mushroom",
    category: "mushrooms",
    calories: 34,
    proteinPer100g: 2.2,
    fiberPer100g: 2.5,
    fatPer100g: 0.5,
    carbsPer100g: 6.8,
    keyNutrients: ["lentinaan (immuunsysteem)", "vitamine D", "selenium", "koper"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Lentinan has immune-modulating properties",
  },
  // ── Peas & beans (Peulvruchten / verse) ───────
  {
    id: "green_beans",
    dutchName: "Sperziebonen",
    englishName: "Green beans (French beans)",
    category: "pod_vegetables",
    calories: 31,
    proteinPer100g: 1.8,
    fiberPer100g: 2.7,
    fatPer100g: 0.1,
    carbsPer100g: 7,
    keyNutrients: ["vitamine K", "vitamine C", "mangaan", "folaat"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "medium",
    notes: "Classic Dutch side dish; versatile and affordable",
  },
  {
    id: "peas_fresh",
    dutchName: "Doperwten (vers)",
    englishName: "Fresh peas",
    category: "pod_vegetables",
    calories: 81,
    proteinPer100g: 5.4,
    fiberPer100g: 5.5,
    fatPer100g: 0.4,
    carbsPer100g: 14,
    keyNutrients: ["vitamine K", "vitamine C", "folaat", "mangaan"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Higher protein and fiber than most vegetables",
  },
  {
    id: "broccoli_sprouts",
    dutchName: "Broccolikiemen",
    englishName: "Broccoli sprouts",
    category: "sprouts",
    calories: 36,
    proteinPer100g: 2.5,
    fiberPer100g: 1.5,
    fatPer100g: 0.5,
    carbsPer100g: 5,
    keyNutrients: ["sulforafaan (100× meer dan broccoli)", "vitamine C", "vitamine K"],
    dietaryFlags: ["vegetarian", "vegan"],
    score: "high",
    notes: "Most concentrated natural source of sulforaphane",
  },
];

// ─────────────────────────────────────────────
// HELPER UTILITIES
// ─────────────────────────────────────────────

/**
 * Filter any ingredient list by dietary flag.
 * @param {Array} list – one of the four exported arrays
 * @param {string} flag – e.g. "vegan", "vegetarian", "dairy", "gluten", "fish"
 * @returns {Array}
 */
export function filterByDiet(list, flag) {
  return list.filter((item) => item.dietaryFlags.includes(flag));
}

/**
 * Filter ingredients by score.
 * @param {Array} list
 * @param {"high"|"medium"|"low"} score
 */
export function filterByScore(list, score) {
  return list.filter((item) => item.score === score);
}

/**
 * Get a combined search object keyed by ingredient id for fast lookup.
 * @returns {Object} { [id]: ingredient }
 */
export function buildLookupMap() {
  const all = [
    ...eiwittenIngredients,
    ...vezelsIngredients,
    ...gezondeVettenIngredients,
    ...groenten,
  ];
  return Object.fromEntries(all.map((item) => [item.id, item]));
}

/**
 * Get all vegan ingredients across every category.
 */
export function getAllVeganIngredients() {
  return filterByDiet(
    [
      ...eiwittenIngredients,
      ...vezelsIngredients,
      ...gezondeVettenIngredients,
      ...groenten,
    ],
    "vegan"
  );
}

/**
 * Summary statistics for a given ingredient list.
 * Returns { count, avgCalories, avgProtein, avgFiber, avgFat }
 */
export function summariseList(list) {
  const n = list.length;
  if (n === 0) return null;
  const sum = (key) => list.reduce((acc, i) => acc + (i[key] ?? 0), 0);
  return {
    count: n,
    avgCalories: +(sum("calories") / n).toFixed(1),
    avgProteinPer100g: +(sum("proteinPer100g") / n).toFixed(1),
    avgFiberPer100g: +(sum("fiberPer100g") / n).toFixed(1),
    avgFatPer100g: +(sum("fatPer100g") / n).toFixed(1),
  };
}

// Default export: all four arrays together for convenience
export default {
  eiwitten: eiwittenIngredients,
  vezels: vezelsIngredients,
  gezondeVetten: gezondeVettenIngredients,
  groenten,
};
